// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vashmbxzrijjissukhei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhc2htYnh6cmlqamlzc3VraGVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzgwNTAsImV4cCI6MjA2OTAxNDA1MH0.9N_dQgQ9h5yTgUgWH1vrHB7N_-O2ppWDklgzcCY-4hI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});