// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhwjwjzvgjwwywssjizn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJod2p3anp2Z2p3d3l3c3NqaXpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODQ2MTYsImV4cCI6MjA2ODc2MDYxNn0.YtZ8tC2l9aoLaa09NEVTpwAe77ux4UyOzbrMrOqUQlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});